// <auto-generated />
using System;
using CarTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarTracker.Data.Migrations
{
    [DbContext(typeof(CarTrackerDbContext))]
    [Migration("20260720003054_AddAssistantTokens")]
    partial class AddAssistantTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarTracker.Data.AssistantToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<int>("ReadCount")
                        .HasColumnType("integer")
                        .HasColumnName("read_count");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("scope");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("WriteCount")
                        .HasColumnType("integer")
                        .HasColumnName("write_count");

                    b.HasKey("Id")
                        .HasName("pk_assistant_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_assistant_tokens_hash");

                    b.ToTable("assistant_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_assistant_tokens_scope", "scope IN ('ReadOnly', 'ReadWrite')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.AssistantWriteAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp_utc");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("tool");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_assistant_write_audits");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_assistant_write_audits_time");

                    b.HasIndex("TokenId")
                        .HasDatabaseName("ix_assistant_write_audits_token_id");

                    b.ToTable("assistant_write_audits", (string)null);
                });

            modelBuilder.Entity("CarTracker.Data.BudgetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualBudget")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("annual_budget");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_budget_categories");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_budget_categories_category");

                    b.HasIndex("VehicleId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_vehicle_category");

                    b.ToTable("budget_categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_budget_categories_annual_budget", "annual_budget >= 0");

                            t.HasCheckConstraint("ck_budget_categories_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.CheckDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CadenceLabel")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("cadence_label");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Guidance")
                        .HasColumnType("text")
                        .HasColumnName("guidance");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_check_definitions");

                    b.HasIndex("VehicleId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_check_definitions_vehicle_name");

                    b.ToTable("check_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_check_definitions_interval", "interval_days > 0");

                            t.HasCheckConstraint("ck_check_definitions_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.CheckLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("check_definition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PerformedOn")
                        .HasColumnType("date")
                        .HasColumnName("performed_on");

                    b.Property<string>("Result")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("result");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_check_logs");

                    b.HasIndex("CheckDefinitionId", "PerformedOn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_check_logs_definition_date");

                    b.ToTable("check_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_check_logs_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_check_logs_result", "result IN ('OK', 'Attention', 'Failed')");

                            t.HasCheckConstraint("ck_check_logs_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.DataAnomaly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("kind");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_data_anomalies");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_anomalies_entity");

                    b.HasIndex("VehicleId", "Status", "Severity")
                        .HasDatabaseName("ix_anomalies_vehicle_status");

                    b.ToTable("data_anomalies", null, t =>
                        {
                            t.HasCheckConstraint("ck_anomalies_kind", "kind IN ('MileageNonMonotonic', 'FuelCostDiscrepancy', 'ImplausibleMpg')");

                            t.HasCheckConstraint("ck_anomalies_resolution_note", "resolution_note <> ''");

                            t.HasCheckConstraint("ck_anomalies_resolved_iff_terminal", "(status = 'Open') = (resolved_at IS NULL)");

                            t.HasCheckConstraint("ck_anomalies_severity", "severity IN ('Error', 'Warning', 'Info')");

                            t.HasCheckConstraint("ck_anomalies_status", "status IN ('Open', 'Accepted', 'Corrected', 'Dismissed')");

                            t.HasCheckConstraint("ck_data_anomalies_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<int?>("ExpenseEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_entry_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasColumnName("file_path");

                    b.Property<int?>("IssueId")
                        .HasColumnType("integer")
                        .HasColumnName("issue_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("ServiceRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("service_record_id");

                    b.Property<string>("Sha256")
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(160)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("ExpenseEntryId")
                        .HasDatabaseName("ix_documents_expense_entry_id");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_documents_issue_id");

                    b.HasIndex("ServiceRecordId")
                        .HasDatabaseName("ix_documents_service_record_id");

                    b.HasIndex("VehicleId", "Type")
                        .HasDatabaseName("ix_documents_vehicle_type");

                    b.ToTable("documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_documents_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_documents_size_bytes", "size_bytes > 0");

                            t.HasCheckConstraint("ck_documents_source", "source IN ('web', 'mcp', 'import', 'seed')");

                            t.HasCheckConstraint("ck_documents_type", "type IN ('V5C', 'Insurance', 'MOT', 'Receipt', 'Photo', 'Manual', 'Other')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.EquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("varchar(60)")
                        .HasColumnName("category");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PurchasedDate")
                        .HasColumnType("date")
                        .HasColumnName("purchased_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVendor")
                        .HasColumnType("varchar(120)")
                        .HasColumnName("source_vendor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("StoredAt")
                        .HasColumnType("varchar(120)")
                        .HasColumnName("stored_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment_items");

                    b.HasIndex("VehicleId", "Status")
                        .HasDatabaseName("ix_equipment_vehicle_status");

                    b.ToTable("equipment_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_equipment_items_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_equipment_items_source", "source IN ('web', 'mcp', 'import', 'seed')");

                            t.HasCheckConstraint("ck_equipment_items_status", "status IN ('Owned', 'OnOrder', 'ToOrder')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.ExpenseCategory", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(24)")
                        .HasColumnName("name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.HasKey("Name")
                        .HasName("pk_expense_categories");

                    b.ToTable("expense_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Fuel",
                            DisplayOrder = 1,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Service",
                            DisplayOrder = 2,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Repair",
                            DisplayOrder = 3,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Parts",
                            DisplayOrder = 4,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Insurance",
                            DisplayOrder = 5,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Tax",
                            DisplayOrder = 6,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "MOT",
                            DisplayOrder = 7,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Wash",
                            DisplayOrder = 8,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Parking",
                            DisplayOrder = 9,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Tools/Equipment",
                            DisplayOrder = 10,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Breakdown",
                            DisplayOrder = 11,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Purchase",
                            DisplayOrder = 12,
                            IsSystem = true
                        },
                        new
                        {
                            Name = "Misc",
                            DisplayOrder = 13,
                            IsSystem = true
                        });
                });

            modelBuilder.Entity("CarTracker.Data.ExpenseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<int?>("FuelEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("fuel_entry_id");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("payment_method");

                    b.Property<int?>("ServiceRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("service_record_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("SubCategory")
                        .HasColumnType("varchar(60)")
                        .HasColumnName("sub_category");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Vendor")
                        .HasColumnType("varchar(120)")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_expense_entries");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_expense_entries_category");

                    b.HasIndex("FuelEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_expense_entries_fuel_entry_id");

                    b.HasIndex("ServiceRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_expense_entries_service_record_id");

                    b.HasIndex("VehicleId", "Category")
                        .HasDatabaseName("ix_expense_entries_vehicle_category");

                    b.HasIndex("VehicleId", "EntryDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_expense_entries_vehicle_date");

                    b.ToTable("expense_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_expense_entries_mileage", "mileage >= 0");

                            t.HasCheckConstraint("ck_expense_entries_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_expense_entries_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.FuelEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("FillLevel")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("fill_level");

                    b.Property<decimal>("Litres")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("litres");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PricePerLitre")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("price_per_litre");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("Station")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("station");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_cost");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_fuel_entries");

                    b.HasIndex("VehicleId", "EntryDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_fuel_entries_vehicle_date");

                    b.HasIndex("VehicleId", "Mileage")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_fuel_entries_vehicle_mileage");

                    b.ToTable("fuel_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_fuel_entries_fill_level", "fill_level IN ('Full', 'Half', 'Quarter')");

                            t.HasCheckConstraint("ck_fuel_entries_litres", "litres > 0");

                            t.HasCheckConstraint("ck_fuel_entries_mileage", "mileage >= 0");

                            t.HasCheckConstraint("ck_fuel_entries_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_fuel_entries_price_per_litre", "price_per_litre > 0");

                            t.HasCheckConstraint("ck_fuel_entries_source", "source IN ('web', 'mcp', 'import', 'seed')");

                            t.HasCheckConstraint("ck_fuel_entries_total_cost", "total_cost > 0");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.Garage", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Contact")
                        .HasColumnType("varchar(120)")
                        .HasColumnName("contact");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Name")
                        .HasName("pk_garages");

                    b.ToTable("garages", null, t =>
                        {
                            t.HasCheckConstraint("ck_garages_notes", "notes <> ''");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionIfWorsens")
                        .HasColumnType("text")
                        .HasColumnName("action_if_worsens");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentObservation")
                        .HasColumnType("text")
                        .HasColumnName("current_observation");

                    b.Property<decimal?>("EstimatedFixCost")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_fix_cost");

                    b.Property<DateOnly>("FirstNoted")
                        .HasColumnType("date")
                        .HasColumnName("first_noted");

                    b.Property<DateOnly?>("LastChecked")
                        .HasColumnType("date")
                        .HasColumnName("last_checked");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("ResolvedDate")
                        .HasColumnType("date")
                        .HasColumnName("resolved_date");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(160)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("VehicleId", "Status", "Severity")
                        .HasDatabaseName("ix_issues_vehicle_status_severity");

                    b.ToTable("issues", null, t =>
                        {
                            t.HasCheckConstraint("ck_issues_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_issues_resolved_date_iff_resolved", "(status = 'Resolved') = (resolved_date IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_severity", "severity IN ('Critical', 'Medium', 'Low')");

                            t.HasCheckConstraint("ck_issues_source", "source IN ('web', 'mcp', 'import', 'seed')");

                            t.HasCheckConstraint("ck_issues_status", "status IN ('Monitoring', 'Resolved')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.MaintenanceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedGarage")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("assigned_garage");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date")
                        .HasColumnName("completed_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("priority");

                    b.Property<int?>("ServiceRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("service_record_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<string>("TargetService")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("target_service");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(160)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_tasks");

                    b.HasIndex("AssignedGarage")
                        .HasDatabaseName("ix_maintenance_tasks_assigned_garage");

                    b.HasIndex("ServiceRecordId")
                        .HasDatabaseName("ix_maintenance_tasks_service_record_id");

                    b.HasIndex("VehicleId", "Status", "Priority")
                        .HasDatabaseName("ix_tasks_vehicle_status");

                    b.ToTable("maintenance_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_maintenance_tasks_source", "source IN ('web', 'mcp', 'import', 'seed')");

                            t.HasCheckConstraint("ck_tasks_completed_date_iff_done", "(status = 'Done') = (completed_date IS NOT NULL)");

                            t.HasCheckConstraint("ck_tasks_garage_workshop_only", "assigned_garage IS NULL OR kind = 'Workshop'");

                            t.HasCheckConstraint("ck_tasks_kind", "kind IN ('DIY', 'Workshop')");

                            t.HasCheckConstraint("ck_tasks_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_tasks_priority", "priority IN ('High', 'Medium', 'Low')");

                            t.HasCheckConstraint("ck_tasks_status", "status IN ('Open', 'InProgress', 'Scheduled', 'Done')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.MileageReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("origin");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date")
                        .HasColumnName("reading_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_mileage_readings");

                    b.HasIndex("VehicleId", "Mileage")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_mileage_readings_vehicle_mileage");

                    b.HasIndex("VehicleId", "ReadingDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_mileage_readings_vehicle_date");

                    b.ToTable("mileage_readings", null, t =>
                        {
                            t.HasCheckConstraint("ck_mileage_readings_mileage", "mileage >= 0");

                            t.HasCheckConstraint("ck_mileage_readings_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_mileage_readings_origin", "origin IN ('purchase', 'manual', 'fuel', 'tyre', 'wash', 'service')");

                            t.HasCheckConstraint("ck_mileage_readings_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Garage")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("garage");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date")
                        .HasColumnName("next_due_date");

                    b.Property<int?>("NextDueMileage")
                        .HasColumnType("integer")
                        .HasColumnName("next_due_mileage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartsReplaced")
                        .HasColumnType("text")
                        .HasColumnName("parts_replaced");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("WorkDone")
                        .HasColumnType("text")
                        .HasColumnName("work_done");

                    b.HasKey("Id")
                        .HasName("pk_service_records");

                    b.HasIndex("Garage")
                        .HasDatabaseName("ix_service_records_garage");

                    b.HasIndex("VehicleId", "ServiceDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_service_records_vehicle_date");

                    b.HasIndex("VehicleId", "Type", "NextDueDate")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_service_records_type_next_due");

                    b.ToTable("service_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_records_mileage", "mileage >= 0");

                            t.HasCheckConstraint("ck_service_records_next_due_mileage", "next_due_mileage >= 0");

                            t.HasCheckConstraint("ck_service_records_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_service_records_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.TyreReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("location");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PsiFrontLeft")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("psi_front_left");

                    b.Property<decimal?>("PsiFrontRight")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("psi_front_right");

                    b.Property<decimal?>("PsiRearLeft")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("psi_rear_left");

                    b.Property<decimal?>("PsiRearRight")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("psi_rear_right");

                    b.Property<decimal?>("PsiSpare")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("psi_spare");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date")
                        .HasColumnName("reading_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("Tool")
                        .HasColumnType("varchar(60)")
                        .HasColumnName("tool");

                    b.Property<decimal?>("TreadFrontLeft")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("tread_front_left");

                    b.Property<decimal?>("TreadFrontRight")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("tread_front_right");

                    b.Property<decimal?>("TreadRearLeft")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("tread_rear_left");

                    b.Property<decimal?>("TreadRearRight")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("tread_rear_right");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_tyre_readings");

                    b.HasIndex("VehicleId", "ReadingDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_tyre_readings_vehicle_date");

                    b.ToTable("tyre_readings", null, t =>
                        {
                            t.HasCheckConstraint("ck_tyre_readings_mileage", "mileage >= 0");

                            t.HasCheckConstraint("ck_tyre_readings_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_tyre_readings_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyStyle")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("body_style");

                    b.Property<string>("Colour")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("colour");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultGarage")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("default_garage");

                    b.Property<string>("Drivetrain")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("drivetrain");

                    b.Property<string>("EngineCode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("engine_code");

                    b.Property<int?>("EngineSizeCc")
                        .HasColumnType("integer")
                        .HasColumnName("engine_size_cc");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("fuel_type");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("model");

                    b.Property<DateOnly?>("MotExpirySeed")
                        .HasColumnType("date")
                        .HasColumnName("mot_expiry_seed");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<int>("PurchaseMileage")
                        .HasColumnType("integer")
                        .HasColumnName("purchase_mileage");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("purchase_price");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("registration");

                    b.Property<string>("RegistrationNormalized")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("registration_normalized")
                        .HasComputedColumnSql("upper(replace(registration, ' ', ''))", true);

                    b.Property<string>("Seller")
                        .HasColumnType("varchar(120)")
                        .HasColumnName("seller");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("status");

                    b.Property<string>("Transmission")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("transmission");

                    b.Property<bool?>("UlezCompliant")
                        .HasColumnType("boolean")
                        .HasColumnName("ulez_compliant");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variant")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("variant");

                    b.Property<decimal?>("VedAnnualCost")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ved_annual_cost");

                    b.Property<DateOnly?>("VedExpiry")
                        .HasColumnType("date")
                        .HasColumnName("ved_expiry");

                    b.Property<string>("Vin")
                        .HasColumnType("varchar(17)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("DefaultGarage")
                        .HasDatabaseName("ix_vehicles_default_garage");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_default")
                        .HasFilter("is_default");

                    b.HasIndex("RegistrationNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_registration");

                    b.ToTable("vehicles", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_fuel_type", "fuel_type IN ('Petrol', 'Diesel', 'Hybrid', 'Electric', 'LPG')");

                            t.HasCheckConstraint("ck_vehicles_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_vehicles_source", "source IN ('web', 'mcp', 'import', 'seed')");

                            t.HasCheckConstraint("ck_vehicles_status", "status IN ('Active', 'Sold', 'SORN')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.WashEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("location");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<DateOnly>("WashDate")
                        .HasColumnType("date")
                        .HasColumnName("wash_date");

                    b.Property<string>("WashType")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("wash_type");

                    b.HasKey("Id")
                        .HasName("pk_wash_entries");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_wash_entries_location");

                    b.HasIndex("VehicleId", "WashDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_wash_entries_vehicle_date");

                    b.ToTable("wash_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_wash_entries_mileage", "mileage >= 0");

                            t.HasCheckConstraint("ck_wash_entries_notes", "notes <> ''");

                            t.HasCheckConstraint("ck_wash_entries_source", "source IN ('web', 'mcp', 'import', 'seed')");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.WashLocation", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Name")
                        .HasName("pk_wash_locations");

                    b.ToTable("wash_locations", null, t =>
                        {
                            t.HasCheckConstraint("ck_wash_locations_notes", "notes <> ''");
                        });
                });

            modelBuilder.Entity("CarTracker.Data.AssistantWriteAudit", b =>
                {
                    b.HasOne("CarTracker.Data.AssistantToken", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assistant_write_audits_assistant_tokens_token_id");
                });

            modelBuilder.Entity("CarTracker.Data.BudgetCategory", b =>
                {
                    b.HasOne("CarTracker.Data.ExpenseCategory", null)
                        .WithMany()
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_categories_expense_categories_category");

                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_categories_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.CheckDefinition", b =>
                {
                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_definitions_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.CheckLog", b =>
                {
                    b.HasOne("CarTracker.Data.CheckDefinition", null)
                        .WithMany()
                        .HasForeignKey("CheckDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_logs_check_definitions_check_definition_id");
                });

            modelBuilder.Entity("CarTracker.Data.DataAnomaly", b =>
                {
                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_anomalies_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.Document", b =>
                {
                    b.HasOne("CarTracker.Data.ExpenseEntry", null)
                        .WithMany()
                        .HasForeignKey("ExpenseEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_expense_entries_expense_entry_id");

                    b.HasOne("CarTracker.Data.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_issues_issue_id");

                    b.HasOne("CarTracker.Data.ServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("ServiceRecordId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_service_records_service_record_id");

                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.EquipmentItem", b =>
                {
                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_items_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.ExpenseEntry", b =>
                {
                    b.HasOne("CarTracker.Data.ExpenseCategory", null)
                        .WithMany()
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_entries_expense_categories_category");

                    b.HasOne("CarTracker.Data.FuelEntry", null)
                        .WithMany()
                        .HasForeignKey("FuelEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_expense_entries_fuel_entries_fuel_entry_id");

                    b.HasOne("CarTracker.Data.ServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("ServiceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_expense_entries_service_records_service_record_id");

                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_entries_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.FuelEntry", b =>
                {
                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fuel_entries_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.Issue", b =>
                {
                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.MaintenanceTask", b =>
                {
                    b.HasOne("CarTracker.Data.Garage", null)
                        .WithMany()
                        .HasForeignKey("AssignedGarage")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_maintenance_tasks_garages_assigned_garage");

                    b.HasOne("CarTracker.Data.ServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("ServiceRecordId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_maintenance_tasks_service_records_service_record_id");

                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_tasks_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.MileageReading", b =>
                {
                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mileage_readings_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.ServiceRecord", b =>
                {
                    b.HasOne("CarTracker.Data.Garage", null)
                        .WithMany()
                        .HasForeignKey("Garage")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_service_records_garages_garage");

                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_records_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.TyreReading", b =>
                {
                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tyre_readings_vehicles_vehicle_id");
                });

            modelBuilder.Entity("CarTracker.Data.Vehicle", b =>
                {
                    b.HasOne("CarTracker.Data.Garage", null)
                        .WithMany()
                        .HasForeignKey("DefaultGarage")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vehicles_garages_default_garage");

                    b.OwnsOne("CarTracker.Data.BreakdownCover", "Breakdown", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateOnly?>("Expiry")
                                .HasColumnType("date")
                                .HasColumnName("breakdown_expiry");

                            b1.Property<string>("PolicyNumber")
                                .HasColumnType("varchar(60)")
                                .HasColumnName("breakdown_policy_number");

                            b1.Property<string>("Provider")
                                .HasColumnType("varchar(80)")
                                .HasColumnName("breakdown_provider");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId")
                                .HasConstraintName("fk_vehicles_vehicles_id");
                        });

                    b.OwnsOne("CarTracker.Data.FluidSpecs", "Fluids", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("AirFilterPart")
                                .HasColumnType("varchar(40)")
                                .HasColumnName("air_filter_part");

                            b1.Property<string>("BrakeFluidSpec")
                                .HasColumnType("varchar(40)")
                                .HasColumnName("brake_fluid_spec");

                            b1.Property<string>("CabinFilterPart")
                                .HasColumnType("varchar(40)")
                                .HasColumnName("cabin_filter_part");

                            b1.Property<decimal?>("CoolantCapacityLitres")
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("coolant_capacity_litres");

                            b1.Property<string>("CoolantSpec")
                                .HasColumnType("varchar(60)")
                                .HasColumnName("coolant_spec");

                            b1.Property<string>("FuelFilterPart")
                                .HasColumnType("varchar(40)")
                                .HasColumnName("fuel_filter_part");

                            b1.Property<decimal?>("FuelTankCapacityLitres")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("fuel_tank_capacity_litres");

                            b1.Property<decimal?>("OilCapacityLitres")
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("oil_capacity_litres");

                            b1.Property<string>("OilFilterPart")
                                .HasColumnType("varchar(40)")
                                .HasColumnName("oil_filter_part");

                            b1.Property<string>("OilSpec")
                                .HasColumnType("varchar(60)")
                                .HasColumnName("oil_spec");

                            b1.Property<string>("SparkPlugPart")
                                .HasColumnType("varchar(40)")
                                .HasColumnName("spark_plug_part");

                            b1.Property<string>("TransmissionOilSpec")
                                .HasColumnType("varchar(60)")
                                .HasColumnName("transmission_oil_spec");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId")
                                .HasConstraintName("fk_vehicles_vehicles_id");
                        });

                    b.OwnsOne("CarTracker.Data.InsurancePolicy", "Insurance", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("CoverType")
                                .HasColumnType("varchar(40)")
                                .HasColumnName("insurance_cover_type");

                            b1.Property<decimal?>("ExcessCompulsory")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("insurance_excess_compulsory");

                            b1.Property<decimal?>("ExcessVoluntary")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("insurance_excess_voluntary");

                            b1.Property<string>("Insurer")
                                .HasColumnType("varchar(80)")
                                .HasColumnName("insurance_insurer");

                            b1.Property<int?>("NcbYears")
                                .HasColumnType("integer")
                                .HasColumnName("insurance_ncb_years");

                            b1.Property<DateOnly?>("PeriodEnd")
                                .HasColumnType("date")
                                .HasColumnName("insurance_period_end");

                            b1.Property<DateOnly?>("PeriodStart")
                                .HasColumnType("date")
                                .HasColumnName("insurance_period_start");

                            b1.Property<string>("PolicyNumber")
                                .HasColumnType("varchar(60)")
                                .HasColumnName("insurance_policy_number");

                            b1.Property<decimal?>("Premium")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("insurance_premium");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId")
                                .HasConstraintName("fk_vehicles_vehicles_id");
                        });

                    b.OwnsOne("CarTracker.Data.TyreSpecs", "Tyres", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal?>("MinTreadMm")
                                .HasColumnType("numeric(3,1)")
                                .HasColumnName("min_tread_mm");

                            b1.Property<decimal?>("PressureFrontLadenPsi")
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("pressure_front_laden_psi");

                            b1.Property<decimal?>("PressureFrontPsi")
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("pressure_front_psi");

                            b1.Property<decimal?>("PressureRearLadenPsi")
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("pressure_rear_laden_psi");

                            b1.Property<decimal?>("PressureRearPsi")
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("pressure_rear_psi");

                            b1.Property<string>("TyreSize")
                                .HasColumnType("varchar(24)")
                                .HasColumnName("tyre_size");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId")
                                .HasConstraintName("fk_vehicles_vehicles_id");
                        });

                    b.Navigation("Breakdown")
                        .IsRequired();

                    b.Navigation("Fluids")
                        .IsRequired();

                    b.Navigation("Insurance")
                        .IsRequired();

                    b.Navigation("Tyres")
                        .IsRequired();
                });

            modelBuilder.Entity("CarTracker.Data.WashEntry", b =>
                {
                    b.HasOne("CarTracker.Data.WashLocation", null)
                        .WithMany()
                        .HasForeignKey("Location")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_wash_entries_wash_locations_location");

                    b.HasOne("CarTracker.Data.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wash_entries_vehicles_vehicle_id");
                });
#pragma warning restore 612, 618
        }
    }
}
